version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:00"
      timezone: America/New_York
    labels:
      - dependencies
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: winreg
        versions:
          - 0.56.x

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "10:15"
      timezone: America/New_York
    labels:
      - dependencies
    open-pull-requests-limit: 5
